### ISSUE TITLE
The resume button is missing.

### ISSUE THREAD

**Issue by thesidshah** [thesidshah/my-website#2]
The resume button is missing.

_Originally posted by @thesidshah in https://github.com/thesidshah/my-website/issues/1#issuecomment-1575577372_

**Comment by Mansi209aps** [comment]
Could you please assign me this issue
I want to work for it

**Comment by thesidshah** [comment]
Hey Mansi! I had resolved the issue, would you be open to working on some other issues? I will be posting a few today
