### ISSUE TITLE
Skills are really big in size and need some interaction

### ISSUE THREAD

**Issue by thesidshah** [thesidshah/my-website#8]
There should be a way to show examples of the skills displayed in the website.

- Click on the skill card to be directed to another window?
- Click on the skill card to get a pop-up of a specific part of the person's git repo 
- Work on Github and Linkedin integration specifically to fetch skillset related data from these sites. Think of alternatives sites such as behance for people with  background other than software development

**Comment by Pulkitxm** [comment]
Can I get assigned and tell me how to start ?

**Comment by thesidshah** [comment]
Yep, sure. I can assign the issue to you; 
Here's the details:
In trying to make the code much more adaptive to different backgrounds there is an issue with skills that do not have a logo and this section does not sum up the person's skillset well. There are examples such as 
![image](https://github.com/thesidshah/my-website/assets/31847975/ee6e28ee-3d7b-4ac9-9348-e7eac9a735af)
 on the internet that can give the viewer a better understanding of the person's skillset. 
Source of image: [YouTube](https://www.youtube.com/watch?v=3aCoZudPEKE&t=4450s)
In the current moment, I am using this code for my website: but if you go through the src/components/Experience/Experience.js file, the intent is to fetch data from json files.

**Comment by Pulkitxm** [comment]
hey the screenshot you provided didn't match with the existing one

the one you showed up is
![image](https://github.com/thesidshah/my-website/assets/65671483/8fb68693-d62e-4d27-90d1-e6b915d96aff)

an the one I am seeing in the code is 
![image](https://github.com/thesidshah/my-website/assets/65671483/e1b70a1e-18e9-4417-a5bb-b7f6b9e69d54)


so I just have to alter these skills , right ?

**Comment by thesidshah** [comment]
That's right @Pulkitxm, the current skills section does not help display skills in an easy to read as well as remember way. But You can always experiment as specified in the end, **prototype** whatever you believe is the best way forward. The screenshot I have provided is from a YouTube video, linked below the image.
